### ISSUE TITLE
[1.12.2] Shop Shelf block recolor oddities.

### ISSUE THREAD

**Issue by SonicX8000** [OreCruncher/Doodads#4]
Minecraft: 1.12.2
Forge: 14.23.5.2778

Mods: 2+
OreLib-1.12.2-3.5.0.1BETA
Patchwork-1.12.2-0.2.0.0BETA
*Plus some other mods that add in different blocks*

-----
Recoloring the Shop Shelf is nice, but... uhh... seems the Shelf doesn't like certain blocks...

![](https://cdn.discordapp.com/attachments/377171551155650560/517810262510665768/weirdshopshelfrecolor.PNG)

Was going to have a fancy glass shelf and noticed that the texture was.... rather off, then figure I try some other blocks. Results were... how should I say... odd.

Transparent blocks like glass have a solid color in the 'invisible' parts of the texture, Bifrost Glass from Botania turns solid instead of transparent which also happens with Ice Blocks, Aurora Block  Types doesn't have any blue/green colors and instead renders as a fading white/grey texture, and... you can have a cobweb texture, as well as an Anvil, Fire, Poppy, perhaps pretty much anything that's a 'block' as a texture.

What got me the most was the Architecture Block recolor, figure it was just going to use the texture that the block had when it was cut but... uhh... nope. Don't think that's fixable due to the way those blocks work.

**Comment by OreCruncher** [comment]
Yep.  Any block with a transparency has the issues you indicate above.  All the reskinning does is grab the texture for the block and applies it.  It doesn't capture any type of transparency attribute or colorizer. Instead of locking down what blocks can be applied I left it wide open even with this side effects.  My hope is that I can figure out a way to at least do the transparency part so things like glass shelves can be made.

EDIT:  Think I found a way.  And it works for solid, cutout (glass) and translucent (stained glass).  Just not sure of the side effects yet.

**Comment by OreCruncher** [comment]
Pushed v0.2.1.0 to CurseForge that has a fix.

**Comment by SonicX8000** [comment]
Using the Aurora Block from Twilight Forest on the shelf still shows as a fading white texture like in the image. I think I recall this happening with ArchitectureCraft where cut blocks showed as a fading white texture. It was fixed in later versions however.

**Comment by OreCruncher** [comment]
I will have to take a look at how AC dealt with it.  I may not be able to do anything about it because of how the block operates.  Currently it just takes the texture and uses that.  For the Aurora Block I suspect it is a texture plus some other rendering fanciness.
